#!/usr/bin/env bash



# This script creates a file with the specified name and content.



# Define the file name.

# This uses parameter expansion to escape the special characters in the file name.

# The resulting file name will be: *\'"Best School"\'*$?****:)

file_name="${1//[*\\'\"\$\?\*:]/\\$&}"



# Define the file content.

file_content="Best School"



# Use the "echo" command to print the file content to a file with the specified name.

# The ">" operator is used to overwrite the file if it already exists,

# and the ">" operator is used to create the file if it does not exist.

# The "-e" option enables interpretation of backslash escapes.

# The "\n" escape sequence adds a new line at the end of the file content.

echo -e "$file_content\n" > "$file_name"


